### ISSUE TITLE
Mixed content

### ISSUE THREAD

**Issue by kaefer3000** [uvdsl/wild-v#1]
Hi,

when running the visualiser on an HTTPS server (as the demo server is), I get an error when accessing a WiLD workflow from an HTTP server.

>  Error on fetch!
>  "TypeError: NetworkError when attempting to fetch resource."

The console tells me that it is a mixed-content problem. Is there a way to tell the employed libraries that mixed-content is OK?

**Comment by uvdsl** [comment]
Hi,
thank you for raising this issue!

Mixed Content is actually not a problem on the application-level, rather it is blocked by your browser [1].
To fix that issue, you can either tell your browser to not check for HTTPS (at your own risk) or ask the maintainer of your requested URI to serve via HTTPS [2].

Cheers!

[1] https://developer.mozilla.org/en-US/docs/Web/Security/Mixed_content
[2] https://developer.mozilla.org/en-US/docs/Web/Security/Mixed_content/How_to_fix_website_with_mixed_content
